# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OoL6KiwS0_19-31F93Zk5FkTfFk3uznj
"""

import heapq

class PuzzleNode:
    def __init__(self, state, parent=None, move=None, depth=0):
        self.state = state
        self.parent = parent
        self.move = move
        self.depth = depth


def get_neighbors(state):
    zero_idx = state.index(0)
    row, col = divmod(zero_idx, 3)
    neighbors = []

    directions = [
        (-1, 0, 'UP'),
        (1, 0, 'DOWN'),
        (0, -1, 'LEFT'),
        (0, 1, 'RIGHT')
    ]

    for dr, dc, move_name in directions:
        new_row, new_col = row + dr, col + dc

        if 0 <= new_row < 3 and 0 <= new_col < 3:
            new_zero_idx = new_row * 3 + new_col
            state_list = list(state)

            state_list[zero_idx], state_list[new_zero_idx] = (
                state_list[new_zero_idx],
                state_list[zero_idx]
            )

            neighbors.append((tuple(state_list), move_name))

    return neighbors


def heuristic(state, goal_state):
    return sum(
        1 for i in range(9)
        if state[i] != 0 and state[i] != goal_state[i]
    )


def a_star(initial_state, goal_state):
    root = PuzzleNode(initial_state)
    priority_queue = []
    counter = 0

    heapq.heappush(
        priority_queue,
        (heuristic(initial_state, goal_state), counter, root)
    )

    visited = {}
    nodes_explored = 0

    while priority_queue:
        f, _, current_node = heapq.heappop(priority_queue)

        if current_node.state in visited:
            if visited[current_node.state] <= current_node.depth:
                continue

        visited[current_node.state] = current_node.depth
        nodes_explored += 1

        if current_node.state == goal_state:
            moves = []
            board_states = []
            curr = current_node

            while curr is not None:
                board_states.append(curr.state)

                if curr.move is not None:
                    moves.append(curr.move)

                curr = curr.parent

            return moves[::-1], nodes_explored, board_states[::-1]

        for next_state, move in get_neighbors(current_node.state):
            new_depth = current_node.depth + 1

            if (next_state not in visited or
                    new_depth < visited[next_state]):
                child = PuzzleNode(
                    next_state,
                    current_node,
                    move,
                    new_depth
                )

                g = new_depth
                h = heuristic(next_state, goal_state)
                counter += 1

                heapq.heappush(
                    priority_queue,
                    (g + h, counter, child)
                )

    return None, nodes_explored, []


def print_board(state):
    for i in range(0, 9, 3):
        print(state[i:i + 3])
    print("-" * 15)


if __name__ == "__main__":
    print("Name: Eashaan M")
    print("USN: 1WA24CS115")
    print("=" * 30)

    initial_board = (
        1, 2, 3,
        4, 0, 5,
        7, 8, 6
    )

    target_board = (
        1, 2, 3,
        4, 5, 6,
        7, 8, 0
    )

    print("\nInitial Board:")
    print_board(initial_board)

    print("Running A* Search...\n")

    moves, total_nodes, board_states = a_star(
        initial_board, target_board
    )

    if moves is not None:
        print("Solution found!")
        print("Total nodes explored:", total_nodes)
        print("Total moves:", len(moves))
        print("Moves sequence:", moves)

        print("\nFinal Board:")
        print_board(board_states[-1])

    else:
        print("No solution found.")