# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OoL6KiwS0_19-31F93Zk5FkTfFk3uznj
"""

class PuzzleNode:
    def __init__(self, state, parent=None, move=None):
        self.state = state
        self.parent = parent
        self.move = move

def get_neighbors(state):
    zero_idx = state.index(0)
    row, col = divmod(zero_idx, 3)
    neighbors = []

    directions = [
        (-1, 0, 'UP'),
        (1, 0, 'DOWN'),
        (0, -1, 'LEFT'),
        (0, 1, 'RIGHT')
    ]

    for dr, dc, move_name in directions:
        new_row, new_col = row + dr, col + dc

        if 0 <= new_row < 3 and 0 <= new_col < 3:
            new_zero_idx = new_row * 3 + new_col
            state_list = list(state)

            state_list[zero_idx], state_list[new_zero_idx] = (
                state_list[new_zero_idx],
                state_list[zero_idx]
            )

            neighbors.append((tuple(state_list), move_name))

    return neighbors

def dfs_8_puzzle(initial_state,
                 goal_state=(1, 2, 3, 4, 5, 6, 7, 8, 0)):
    stack = [PuzzleNode(initial_state)]
    visited = set()
    nodes_explored = 0

    while stack:
        current_node = stack.pop()

        if current_node.state in visited:
            continue

        visited.add(current_node.state)
        nodes_explored += 1

        if current_node.state == goal_state:
            path = []
            board_states = []
            curr = current_node

            while curr is not None:
                board_states.append(curr.state)

                if curr.move is not None:
                    path.append(curr.move)

                curr = curr.parent

            return path[::-1], nodes_explored, board_states[::-1]

        for next_state, move in get_neighbors(current_node.state):
            if next_state not in visited:
                stack.append(
                    PuzzleNode(next_state, current_node, move)
                )

    return None, nodes_explored, []

def print_board(state):
    for i in range(0, 9, 3):
        print(state[i:i + 3])
    print("-" * 15)

if __name__ == "__main__":
    print("Name: Eashaan M")
    print("USN: 1WA24CS115")
    print("=" * 30)

    initial_board = (
        1, 2, 3,
        4, 0, 5,
        7, 8, 6
    )

    target_board = (
        1, 2, 3,
        4, 5, 6,
        7, 8, 0
    )

    print("\nInitial Board:")
    print_board(initial_board)

    print("Running DFS...\n")

    moves, total_nodes, board_states = dfs_8_puzzle(
        initial_board, target_board
    )

    if moves is not None:
        print("Solution found!")
        print("Total nodes explored:", total_nodes)
        print("Total moves:", len(moves))
        print("Moves sequence:", moves)

        print("\nFinal Board:")
        print_board(board_states[-1])

    else:
        print("No solution found.")