# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OoL6KiwS0_19-31F93Zk5FkTfFk3uznj
"""

class PuzzleNode:
    def __init__(self, state, parent=None, move=None):
        self.state = state
        self.parent = parent
        self.move = move


def get_neighbors(state):
    zero_idx = state.index(0)
    row, col = divmod(zero_idx, 3)
    neighbors = []

    directions = [
        (-1, 0, 'UP'),
        (1, 0, 'DOWN'),
        (0, -1, 'LEFT'),
        (0, 1, 'RIGHT')
    ]

    for dr, dc, move_name in directions:
        new_row, new_col = row + dr, col + dc

        if 0 <= new_row < 3 and 0 <= new_col < 3:
            new_zero_idx = new_row * 3 + new_col
            state_list = list(state)

            state_list[zero_idx], state_list[new_zero_idx] = (
                state_list[new_zero_idx],
                state_list[zero_idx]
            )

            neighbors.append((tuple(state_list), move_name))

    return neighbors


def depth_limited_search(node, goal_state, limit, visited, nodes):
    nodes[0] += 1

    if node.state == goal_state:
        return node

    if limit == 0:
        return None

    visited.add(node.state)

    for next_state, move in get_neighbors(node.state):
        if next_state not in visited:
            child = PuzzleNode(next_state, node, move)

            result = depth_limited_search(
                child, goal_state, limit - 1, visited, nodes
            )

            if result is not None:
                return result

    return None


def idfs_8_puzzle(initial_state,
                  goal_state=(1, 2, 3, 4, 5, 6, 7, 8, 0),
                  max_depth=50):
    total_nodes = 0

    for depth in range(max_depth + 1):
        visited = set()
        nodes = [0]

        root = PuzzleNode(initial_state)

        result = depth_limited_search(
            root, goal_state, depth, visited, nodes
        )

        total_nodes += nodes[0]

        if result is not None:
            moves = []
            board_states = []
            curr = result

            while curr is not None:
                board_states.append(curr.state)

                if curr.move is not None:
                    moves.append(curr.move)

                curr = curr.parent

            return moves[::-1], total_nodes, board_states[::-1], depth

    return None, total_nodes, [], -1


def print_board(state):
    for i in range(0, 9, 3):
        print(state[i:i + 3])
    print("-" * 15)


if __name__ == "__main__":
    print("Name: Eashaan M")
    print("USN: 1WA24CS115")
    print("=" * 30)

    initial_board = (
        1, 2, 3,
        4, 0, 5,
        7, 8, 6
    )

    target_board = (
        1, 2, 3,
        4, 5, 6,
        7, 8, 0
    )

    print("\nInitial Board:")
    print_board(initial_board)

    print("Running IDFS...\n")

    moves, total_nodes, board_states, depth = idfs_8_puzzle(
        initial_board, target_board
    )

    if moves is not None:
        print("Solution found!")
        print("Total nodes explored:", total_nodes)
        print("Solution depth:", depth)
        print("Total moves:", len(moves))
        print("Moves sequence:", moves)

        print("\nFinal Board:")
        print_board(board_states[-1])

    else:
        print("No solution found within the maximum depth.")